[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "river_computing"
authors = [{name = "Giang (River) Nguyen", email = "nttg8100@gmail.com"}]
dynamic = ["version", "description"]
